---
- name: install packages
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: open minio port 9000
  command: ufw allow 9000/tcp

- name: open minio port 9001
  command: ufw allow 9001/tcp

- name: open http port 80
  command: ufw allow 80/tcp

- name: enable firewall
  shell: |
    set -o pipefail
    echo "y" | ufw enable
  args:
    executable: /bin/bash
