---
- name: Update and upgrade the machine
  apt:
    upgrade: dist
    update_cache: true

- name: download minio
  get_url:
    url: 'https://dl.min.io/server/minio/release/linux-amd64/minio'
    dest: '/tmp/minio'
    mode: '0700'

- name: copy minio binary
  copy:
    src: '/tmp/minio'
    dest: '/usr/local/bin/'
    remote_src: true
    owner: root
    group: root
    mode: 755

- name: Copy config file
  template:
    src: 'minio.config.j2'
    dest: '/etc/default/minio.config'
    owner: root
    group: root
    mode: '0644'

- name: Create data folder
  file:
    path: '/home/{{ ansible_user }}/data'
    state: directory
    owner: '{{ansible_user}}'
    group: '{{ansible_user}}'
    mode: '0755'

- name: Copy systemd file
  template:
    src: 'minio.service.j2'
    dest: '/etc/systemd/system/minio.service'
    owner: root
    group: root
    mode: 755

- name: start minio service
  systemd:
    name: minio
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
