---
- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Disable the default nginx site
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent

- name: create nginx config for minio
  template:
    src: minio.conf.j2
    dest: '/etc/nginx/sites-enabled/{{ minio_url }}.conf'

- name: create nginx config for snapshots
  template:
    src: snapshots.conf.j2
    dest: '/etc/nginx/sites-enabled/{{ storage_url }}.conf'

- name: Start Nginx
  service:
    name: nginx
    state: restarted
    enabled: true
